version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports: 
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  prometheus:
    image: prom/prometheus
    restart: always
    volumes: 
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - 9090:9090 # UI displaying the metrics
  redis:
    image: redis
    ports:
      - 6379:6379
  collector-gateway:
    image: otel/opentelemetry-collector:latest
    restart: always
    volumes: 
      - ./conf/collector-gateway.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics (where Prometheus picks up the metrics)
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver/collector
      - "4318:4318"   # OTLP HTTP receiver/collector
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger
      - prometheus
