global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus

    scrape_interval: 1s
    scrape_timeout: 1s
    honor_labels: true

    static_configs:
      - targets: ['collector-gateway:8889']
